import time

print("welcome to the shape calculator")
time.sleep(1.5)
print ("the shapes that are available are:")
time.sleep(1.5)
z = ["circle","rectangle","triangle","sqaure","semicircle"]
print(z[0])
time.sleep(0.5)
print(z[1])
time.sleep(0.5)
print(z[2])
time.sleep(0.5)
print(z[3])
time.sleep(0.5)
print(z[4])
time.sleep(1.5)
a = input("what shape are you using")
if a == "circle":
    d = int(input('enter the radius of the circle'))
    print ('the circumfrence of the circle is:')
    print(2*3.14159265358979323*d)
    print ('the diameter of the circle is:')
    print (2*d)
    print ('the area of the circle is:')
    print (3.14159265358979323*(d*d))
elif a == "rectangle":
    b = int(input('enter the length of the rectangle is:'))
    c = int(input("enter the width of the rectangle is:"))
    print('the perimenter of the rectangle is:')
    print(2*b+2*c)
    print('the area of the rectangle is:')
    print(b*c)
elif a == "triangle": 
    e = int(input('enter the length of the triangle:'))
    f = int(input("enter the width of the triangle:"))
    g = (e*e+f*f)
    h = (g**(1/2)) 
    print("the hypotenuse of the triangle is:")
    print(h)
    print ('the perimenter of the triangle is:')
    print (e+f+h)
    print ("the area of the triangle is:")
    print((e*f)/2)
elif a == "sqaure":
    b = int(input('enter the length of the sqaure:'))
    print("the area of the sqaure is:")
    print(b**2)
    print ('the perimenter of the triangle is:')
    print(b*4)
elif a == "semicircle":
    b = int(input("enter the radius pf the semicircle:"))
    c = (2*b)
    print("the perimeter of the semicircle is:")
    print(0.5*(2*3.14159265358979323*b)+c)
    print('the area of the cemicircle is:')
    print(0.5*(3.14159265358979323*(b**2)))